name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # official action from GitHub, no pinning required
      - name: Put files into a directory
        run: |
          mkdir public
          cp index.html public/
      - name: Upload page
        uses: actions/upload-pages-artifact@v3  # official action from GitHub, no pinning required
        with:
          path: public

  publish:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5  # official action from GitHub, no pinning required
